service: serverless-indexer

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${file(./.env.yml):AWS_PROFILE}
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true
  environment:
    ALGOLIA_ID: ${self:custom.awsSecrets.ALGOLIA_ID}
    ALGOLIA_ADMIN_KEY: ${self:custom.awsSecrets.ALGOLIA_ADMIN_KEY}

custom:
  awsSecrets: ${ssm:/aws/reference/secretsmanager/serverless-indexer~true}

functions:
  addIndex:
    handler: handler.addIndex
    events:
      - http:
          path: add-index
          method: post

  deleteIndex:
    handler: handler.deleteIndex
    events:
      - http:
          path: delete-index
          method: post

  updateIndex:
    handler: handler.updateIndex
    events:
      - http:
          path: update-index
          method: post

plugins:
  - serverless-offline
