environment:
  PRD_ALGOLIA_ID: ${PRD_ALGOLIA_ID}
  PRD_ALGOLIA_ADMIN_KEY: ${PRD_ALGOLIA_ADMIN_KEY}

  DEV_ALGOLIA_ID: ${DEV_ALGOLIA_ID}
  DEV_ALGOLIA_ADMIN_KEY: ${DEV_ALGOLIA_ADMIN_KEY}

  NODE_ENV: ${NODE_ENV}

packages:
  - name: hashnode
    functions:
      - name: add-or-update-record
        main: 'addOrUpdateRecord'
        runtime: nodejs:18

      - name: delete-record
        main: 'deleteRecord'
        runtime: nodejs:18
